Repository weiboad/kafka-php, pull requests merged in 2018-02, with the labels that each got.

#192 Fix coding standard issues
  example/Producer.php
  example/SaslSocket.php
  example/protocol/ApiVerions.php
  example/protocol/CommitOffset.php
  example/protocol/DescribeGroups.php
  example/protocol/Fetch.php
  example/protocol/FetchOffset.php
  example/protocol/Group.php
  example/protocol/Heartbeat.php
  example/protocol/JoinGroup.php
  example/protocol/LeaveGroup.php
  example/protocol/ListGroup.php
  example/protocol/MetaData.php
  example/protocol/Offset.php
  example/protocol/Produce.php
  example/protocol/SaslHandShake.php
  example/protocol/SyncGroup.php
  src/Producer/SyncProcess.php
  src/Protocol.php
  src/Sasl/Mechanism.php
  tests/Base/Sasl/PlainTest.php
Labels: Bug

#181 Exceptions when producing invalid messages + custom exception on reading socket
  src/CommonSocket.php
  src/Exception/InvalidRecordInSet.php
  src/Exception/Socket.php
  src/Producer/Process.php
  src/Producer/RecordValidator.php
  src/Producer/SyncProcess.php
  tests/Base/Producer/RecordValidatorTest.php
  tests/Base/SocketTest.php
  tests/Functional/Ticket/GH181Test.php
Labels: Improvement

#195 Sort properties in config documentation
  docs/Configure.md
Labels: Documentation
